### ISSUE TITLE
Running on Raspberry-Pi

### ISSUE THREAD

**Issue by Digital0** [andresoviedo/google-drive-ftp-adapter#24] opened 2018-03-01 00:28 UTC
I have installed and tested java on my raspberry pi. So, why when do I get an error whenever I run the file?

**Comment by andresoviedo** [comment] 2018-03-13 15:13
Whats the error you have when running the google-drive-ftp-adapter?

**Comment by johnjjsmith** [comment] 2018-05-20 18:35
You have to compile libsqlitejdbc.so for Raspberry Pi for Google Drive FTP Adapter to work on it.

You can download the jar with all dependencies here: [google-drive-ftp-adapter-jar-with-dependencies.zip](https://github.com/andresoviedo/google-drive-ftp-adapter/files/2020560/google-drive-ftp-adapter-jar-with-dependencies.zip) (rename zip to jar)

**Comment by andresoviedo** [comment] 2019-02-10 11:59
Hello. I don't have a Rapsberry and I don't have much time to emulate one.

So, if you want to contribute, could you please change the sqlite-jdbc maven dependency in pom.xml with latest version and rebuild package so you can test it?  You can try with this one:


    <dependency>
      <groupId>org.xerial</groupId>
      <artifactId>sqlite-jdbc</artifactId>
      <version>3.25.2</version>
    </dependency>

If it works, please give us your feedback so I can upgrade it. Many thanks

**Comment by andresoviedo** [comment] 2019-02-10 12:04
Duplicate of #12

**Closed by andresoviedo** 2019-02-10 12:04 UTC
Labels: enhancement, good first issue, help wanted
